version: '3'
services:
  house-cmu:
    image: ${DOCKERHUB_USERNAME}/house-cmu:latest
    ports:
      - "5051:5050"
    networks:
      - app-network
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  house-mse:
    image: ${DOCKERHUB_USERNAME}/house-mse:latest
    ports:
      - "5050:5050"
    networks:
      - app-network
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  platform:
    image: ${DOCKERHUB_USERNAME}/platform:latest
    depends_on:
      mysql-container:
        condition: service_healthy
      house-cmu:
        condition: service_started
      house-mse:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - app-network
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mysql-container:
    image: ${DOCKERHUB_USERNAME}/mysql-container:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-storage:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql-storage:

networks:
  app-network:
    driver: bridge