name: Build and Test

on:
  push:
    branches:
      - main
      - armaan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java 11 or 17, depending on your project)
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'

      # Step 3: Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches  
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Run Gradle build and tests
      - name: Build and Test
        run: |
          cd smart-home
          cd Platform
          ./gradlew clean build

      - name: set up pytest
        run: pip install pytest requests beautifulsoup4

      - name: Run System tests
        working-directory: ./smart-home
        run: pytest system_tests.py

      - name: Jacoco report
        id: jacoco
        working-directory: ./smart-home/Platform
        run: ./gradlew jacocoTestReport
